network:
  ethernets:
    eno1:
      addresses:
      - 192.168.3.2/23
      nameservers:
        addresses:
        - 1.1.1.1
        search: []
      routes:
      - to: default
        via: 192.168.2.1
    enp5s0:
      addresses:
      - 192.168.5.2/23
      nameservers:
        addresses: []
        search: []
  version: 2
  wifis:
    wlp3s0:
      activation-mode: off
      access-points:
        BananaShack-24:
          password: REDACTED
      dhcp4: false