network:
  version: 2
  ethernets:
    eno1:
      addresses:
      - "192.168.3.1/23"
      nameservers:
        addresses:
        - 9.9.9.9
        search: []
      routes:
      - to: "default"
        via: "192.168.2.1"
    enp5s0:
      addresses:
      - "192.168.5.1/23"
  wifis:
    wlp3s0:
      activation-mode: off
      addresses:
      - "192.168.2.80/23"
      dhcp4: false
      nameservers:
        addresses:
        - 9.9.9.9
        search: []
      routes:
      - to: "default"
        via: "192.168.2.1"
      access-points:
        "BananaShack-24":
          auth:
            key-management: "psk"
            password: "REDACTED"