# Place in /etc/rancher/k3s/config.yaml
server: https://192.168.3.2:6443
tls-san: 192.168.3.1,192.168.5.1,beehive1,beehive1.home.arpa
node-ip: 192.168.3.1
token: REDACTED_ K3S_TOKEN_VALUE
write-kubeconfig-mode: 644

# Networking options (defaults for reference, commented out)
# cluster-cidr: 10.42.0.0/16
# cluster-domain: cluster.local
# cluster-dns: 10.43.0.10
# service-cidr: 10.43.0.0/16
# service-node-port-range: 30000-32767
# Set flannel to use IP routes to control traffic instead of VXLAN encapsulation. This
# should provide better performance:
flannel-backend: host-gw
# If we later choose to disable flannel, we can do so with the following:
# flannel-backend: none
# disable-network-policy: true
flannel-iface: enp5s0

# Comma separated list of services to disable.
# Available options: coredns, local-storage, metrics-server, servicelb, traefik
# ? Should we disable local-storage?
disable: servicelb,traefik
# Do we need this if we disable servicelb and install metallb?
# disable-cloud-controller: true

embedded-registry: true

# For longhorn deployment, node annotations also are needed, but are not supported by
# k3s at deployment time:
node-label:
  - node.longhorn.io/create-default-disk=config

# Set device ownership from security context in containerd
# This WAS and experimental feature in and earlier k3s, but now appears to be removed.
# We will need to use the config-v3.toml.tmpl file to set this.
# containerd-device-ownership-from-security-context: true