kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-ssd-double
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
  diskSelector: "ssd,fast"
