replicationEnabled:
  secrets: true
  configMaps: true
  roles: false
  roleBindings: false
  serviceAccounts: false

serviceAccount:
  create: true
  annotations: {}
  name:
  privileges:
    - apiGroups:
        - ""
        # - "apps"
        # - "extensions"
      resources: 
        - "secrets"
        - "configmaps"
        # - "roles"
        # - "rolebindings"
        - "cronjobs"
        - "deployments"
        - "events"
        - "ingresses"
        - "jobs"
        # - "pods"
        # - "pods/attach"
        # - "pods/exec"
        # - "pods/log"
        # - "pods/portforward"
        # - "services"
    - apiGroups:
        - "batch"
      resources:
        - "configmaps"
        - "cronjobs"
        - "deployments"
        - "events"
        - "ingresses"
        - "jobs"
        # - "pods"
        # - "pods/attach"
        # - "pods/exec"
        # - "pods/log"
        # - "pods/portforward"
        - "services"