apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-le-prod
spec:
  acme:
    email: REDACTED@DOMAIN.COM
    preferredChain: ISRG Root X1
    privateKeySecretRef:
      name: cert-manager-acme-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          email: REDACTED@DOMAIN.COM
          apiKeySecretRef:
            name: cloudflare-api-key
            key: api-key