apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-2x-replica
parameters:
  allowVolumeExpansion: "true"
  fsType: xfs
  ioTimeout: "60"
  poolAffinityTopologyLabel: |
    pool: nvme-ssd
  protocol: nvmf
  repl: "2"
  thin: "false"
provisioner: io.openebs.csi-mayastor