# Use the configuration sample from the k3s docs to serve as a template.
# NOTE that we need to include the "configuration_path" key in the IPAM section.
# ALSO, we only can use "range": with a CIDR notation.  the rangeStart and rangeEnd keys
# seen in other docs appear to have been deprecated/removed.

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: storage-net
  namespace: kube-system
spec:
  config: |-
    {
      "cniVersion": "1.0.0",
      "type": "macvlan",
      "master": "enp5s0",
      "mode": "bridge",
      "ipam": {
          "type": "whereabouts",
          "range": "192.168.4.0/23",
          "range_start": "192.168.4.1",
          "range_end": "192.168.4.255",
          "configuration_path": "/var/lib/rancher/k3s/agent/etc/cni/net.d/whereabouts.d/whereabouts.conf"
      }
    }

# Note: we tried adding this to the ipam config, but it caused permissions errors:
# "node_slice_size": "/26
# Apparently this config option requires API rights that were not included in the Multus
# helm chart.
